spring.application.name=malang

#?? ??
server.port=8088

#DB??
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=

#JPA
spring.jpa.database-platform=
spring.jpa.hibernate.ddl-auto=update

#SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true